agent_name: new_agent
author: kevin
version: 0.1.0
license: Apache-2.0
description: ''
aea_version: '>=1.55.0, <2.0.0'
fingerprint: {}
fingerprint_ignore_patterns: []
connections:
- eightballer/http_client:0.1.0:bafybeihli73baanti52hpp3gnsgvfsx5rkpfprnzazmi3pamwafvngvnu4
- eightballer/http_server:0.1.0:bafybeicsx5ayj37c27a4ffsd4f6ydr5lsed53rn3tkdzxar22da5raaoqm
- eightballer/prometheus:0.1.1:bafybeib75z6akopysvkfbmdom4v5ajsx7rz5piachojppiukxs7saxrh64
- eightballer/redis_client:0.1.0:bafybeidsk6u3nqntuyhabmwac773twvomowxmohxmgxmyz2tv4nppgso4e
- valory/ledger:0.19.0:bafybeigntoericenpzvwejqfuc3kqzo2pscs76qoygg5dbj6f4zxusru5e
contracts:
- eightballer/olas_erc20:0.1.0:bafybeigovz3fg5g46f5geyy33fpvuof3ewktslxswipk37fqpmfj42uysi
protocols:
- eightballer/default:0.1.0:bafybeigyjou5vodsbobshik523ykweos7ir4qz2lw4h6kjkqjlwrk4p3fa
- eightballer/http:0.1.0:bafybeieexnvev3uegukhfnackqq2ooceiqcnu7q7e4w73wyohvfjod6bqq
- eightballer/prometheus:1.0.0:bafybeibvuazvki5pbeakpvcjm7icgf4wosacpcfnpyr4tk5dz3egoqny4a
- eightballer/pubsub:0.1.0:bafybeiakcgcainnriztgv47nn3o3vaakh6wmgpf6ztx6b4ubngmaaut5pe
- open_aea/signing:1.0.0:bafybeig2d36zxy65vd7fwhs7scotuktydcarm74aprmrb5nioiymr3yixm
- valory/contract_api:1.0.0:bafybeidgu7o5llh26xp3u3ebq3yluull5lupiyeu6iooi2xyymdrgnzq5i
- valory/ledger_api:1.0.0:bafybeihdk6psr4guxmbcrc26jr2cbgzpd5aljkqvpwo64bvaz7tdti2oni
skills:
- eightballer/prometheus:0.1.0:bafybeicmuxgesotcd7s66scoftahjaoiijcm4pjiblrubnr47mvgp233em
- kevin/whale_watcher_abci_app:0.1.0:bafybeidigjujlnwdiylvhfaaq66lx7bked4pni5orvhnwddieb25ji6laq
customs: []
default_ledger: ethereum
required_ledgers:
- ethereum
default_routing: {}
connection_private_key_paths: {}
private_key_paths: {}
logging_config:
  disable_existing_loggers: true
  formatters:
    standard:
      format: '%(asctime)s [%(levelname)s] %(name)s: %(message)s'
  handlers:
    console:
      class: rich.logging.RichHandler
      level: INFO
    logfile:
      class: logging.FileHandler
      filename: log.txt
      formatter: standard
      level: INFO
  loggers:
    aea:
      handlers:
      - console
      - logfile
      level: INFO
      propagate: false
  version: 1
dependencies:
  open-aea-ledger-cosmos: {}
  open-aea-ledger-ethereum: {}
  open-aea-ledger-solana: {}
  rich: {}
default_connection: null
---
public_id: eightballer/http_server:0.1.0:bafybeicp3ubkonolxjgnwgqmaz624qduwzzz74fbjizu77lyvnpo77uv7u
type: connection
config:
  host: 0.0.0.0
  port: 8888
  target_skill_id: kevin/whale_watcher_abci_app:0.1.0
---
public_id: eightballer/redis_client:0.1.0:bafybeid7u7cx2smnb3iz6zs6gt3k4ijwevm6yqqfo4pmziqoubl2p52ele
type: connection
config:
  host: localhost
  port: 6379
  target_skill_id: eightballer/redis_subscriber:0.1.0
---
public_id: valory/ledger:0.19.0:bafybeigntoericenpzvwejqfuc3kqzo2pscs76qoygg5dbj6f4zxusru5e
type: connection
config:
  ledger_apis:
    ethereum:
      address: https://mainnet.base.org
      chain_id: 8453
