name: new_service
author: kevin
version: 0.1.0
description: A new service, scaffolded by the Adev cli from kevin/new_agent:0.1.0
aea_version: '>=1.0.0, <2.0.0'
license: apache-2.0
fingerprint: {}
fingerprint_ignore_patterns: []
agent: kevin/new_agent:0.1.0:bafybeih3p2doneovlerk4jygjoolvj742sqqqqgwtdrt6myh64i2r6gak4
number_of_agents: 1
deployment:
  agent:
    ports: {}
    volumes: {}
---
public_id: eightballer/http_server:0.1.0:bafybeicp3ubkonolxjgnwgqmaz624qduwzzz74fbjizu77lyvnpo77uv7u
type: connection
config:
  host: 0.0.0.0
  port: 8888
  target_skill_id: kevin/whale_watcher_abci_app:0.1.0
---
public_id: eightballer/redis_client:0.1.0:bafybeid7u7cx2smnb3iz6zs6gt3k4ijwevm6yqqfo4pmziqoubl2p52ele
type: connection
config:
  host: localhost
  port: 6379
  target_skill_id: eightballer/redis_subscriber:0.1.0
---
public_id: valory/ledger:0.19.0:bafybeigntoericenpzvwejqfuc3kqzo2pscs76qoygg5dbj6f4zxusru5e
type: connection
config:
  ledger_apis:
    ethereum:
      address: https://mainnet.base.org
      chain_id: 8453
