version: "2.4"
services:

  finishedwhalewatcherLuaO_tm_0:
    user: "1000"
    mem_limit: 1024m
    mem_reservation: 256M
    cpus: 0.5
    container_name: finishedwhalewatcherLuaO_tm_0
    hostname: finishedwhalewatcherLuaO_tm_0
    image: "valory/open-autonomy-tendermint:0.19.2"
    restart: always
    environment:
      - ID=0
      - PROXY_APP=tcp://finishedwhalewatcherLuaO_abci_0:26658
      - TMHOME=/tendermint/node0
      - CREATE_EMPTY_BLOCKS=true
      - DEV_MODE=0
      - LOG_FILE=/logs/node_0.txt
      - LOG_LEVEL=INFO
      - WRITE_TO_LOG=true
    working_dir: /tendermint
    command: ["run", "--no-reload", "--host=0.0.0.0", "--port=8080",]
    depends_on:
      finishedwhalewatcherLuaO_abci_0:
        condition: service_healthy
    networks:
      service_finished_whale_watcher_localnet:
        ipv4_address: 192.167.12.3
    volumes:
      - ./nodes:/tendermint:Z
      - ./persistent_data/logs:/logs:Z

  finishedwhalewatcherLuaO_abci_0:
    mem_reservation: 256M
    mem_limit: 1024M
    cpus: 1.0
    container_name: finishedwhalewatcherLuaO_abci_0
    image: eightballer/oar-whale_watcher:bafybeicr5wi5r4f272rxybgb4jcpksnylktm5qnzi3ldltbdxnjk4yq24e
    env_file: agent_0.env
    networks:
      service_finished_whale_watcher_localnet:
        ipv4_address: 192.167.12.2
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./persistent_data/logs:/logs:Z
      - ./agent_keys/agent_0:/agent_key:Z

networks:
  service_finished_whale_watcher_localnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.167.12.0/24
